const PACKS = [
  {
    id: 'agency',
    name: 'Agency Automation Pack',
    file: 'agency-sample.json',
    industries: ['agency', 'marketing agency', 'creative agency', 'consulting'],
    keywords: ['client report', 'status update', 'project tracking', 'retainer', 'client management'],
    description: 'Client status reports, project tracking, retainer reminders, agency billing workflows.',
    price: '$49',
    url: 'https://payhip.com/b/uwX9J',
  },
  {
    id: 'bookkeeping',
    name: 'Bookkeeping Automation Pack',
    file: 'bookkeeping-sample.json',
    industries: ['bookkeeping', 'accounting', 'finance', 'bookkeeper'],
    keywords: ['invoice', 'reconciliation', 'receipt', 'expense', 'BAS', 'payroll', 'cashflow'],
    description: 'Invoice processing, bank reconciliation alerts, expense categorisation, BAS reminders.',
    price: '$49',
    url: 'https://payhip.com/b/Vgq75',
  },
  {
    id: 'content-creator',
    name: 'Content Creator Automation Pack',
    file: 'content-creator-sample.json',
    industries: ['content creator', 'youtube', 'blogger', 'influencer', 'media'],
    keywords: ['publish', 'schedule', 'social post', 'newsletter', 'content calendar', 'repurpose'],
    description: 'Content scheduling, cross-platform publishing, newsletter automation, analytics reports.',
    price: '$49',
    url: 'https://payhip.com/b/lp8cF',
  },
  {
    id: 'customer-onboarding',
    name: 'Customer Onboarding Automation Pack',
    file: 'customer-onboarding-sample.json',
    industries: ['saas', 'software', 'service business', 'b2b'],
    keywords: ['onboarding', 'welcome', 'new customer', 'setup', 'trial', 'activation', 'kickoff'],
    description: 'Welcome sequences, trial activation flows, kickoff meeting scheduling, onboarding checklists.',
    price: '$49',
    url: 'https://payhip.com/b/BtlNy',
  },
  {
    id: 'customer-support',
    name: 'Customer Support Automation Pack',
    file: 'customer-support-sample.json',
    industries: ['support', 'helpdesk', 'customer service', 'ecommerce'],
    keywords: ['ticket', 'support', 'escalation', 'refund', 'complaint', 'csat', 'response'],
    description: 'Ticket routing, escalation rules, CSAT surveys, refund processing, auto-response templates.',
    price: '$49',
    url: 'https://payhip.com/b/mS2iJ',
  },
  {
    id: 'dental',
    name: 'Dental Clinic Automation Pack',
    file: 'dental-sample.json',
    industries: ['dental', 'dentist', 'oral health', 'dental clinic'],
    keywords: ['appointment', 'recall', 'reminder', 'treatment plan', 'patient follow-up'],
    description: 'Appointment reminders, recall sequences, post-visit follow-ups, treatment plan follow-ups.',
    price: '$49',
    url: 'https://payhip.com/b/G8zgK',
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce Automation Pack',
    file: 'ecommerce-sample.json',
    industries: ['ecommerce', 'shopify', 'woocommerce', 'online store', 'retail'],
    keywords: ['order', 'abandoned cart', 'shipping', 'review', 'refund', 'inventory', 'product'],
    description: 'Order processing, abandoned cart recovery, shipping notifications, review requests, inventory alerts.',
    price: '$49',
    url: 'https://payhip.com/b/KRYh3',
  },
  {
    id: 'education-events',
    name: 'Education + Events Automation Pack',
    file: 'education-events-sample.json',
    industries: ['education', 'events', 'conference', 'workshop', 'training'],
    keywords: ['registration', 'attendee', 'reminder', 'certificate', 'feedback', 'event', 'course'],
    description: 'Event registration flows, attendee reminders, post-event feedback, certificate generation.',
    price: '$49',
    url: 'https://payhip.com/b/8hnPA',
  },
  {
    id: 'elearning',
    name: 'E-Learning + Course Creator Pack',
    file: 'elearning-sample.json',
    industries: ['elearning', 'course creator', 'online course', 'coaching', 'tutoring'],
    keywords: ['student', 'lesson', 'progress', 'completion', 'enrollment', 'quiz', 'certificate'],
    description: 'Student enrollment flows, lesson reminders, progress tracking, completion certificates.',
    price: '$49',
    url: 'https://payhip.com/b/9d4L5',
  },
  {
    id: 'event-mgmt',
    name: 'Event Management Automation Pack',
    file: 'event-mgmt-sample.json',
    industries: ['event management', 'wedding planner', 'corporate events', 'conference organiser'],
    keywords: ['venue', 'vendor', 'guest', 'rsvp', 'timeline', 'brief', 'run sheet'],
    description: 'Vendor briefings, guest communication sequences, RSVP tracking, event run sheet automation.',
    price: '$49',
    url: 'https://payhip.com/b/bdw35',
  },
  {
    id: 'finance',
    name: 'Finance + Accounting Automation Pack',
    file: 'finance-sample.json',
    industries: ['finance', 'accounting', 'financial services', 'cfo', 'finance team'],
    keywords: ['report', 'forecast', 'budget', 'variance', 'cashflow', 'accounts payable', 'accounts receivable'],
    description: 'Financial report generation, budget variance alerts, cashflow forecasting, AP/AR workflows.',
    price: '$49',
    url: 'https://payhip.com/b/YxIh9',
  },
  {
    id: 'freelancer',
    name: 'Freelancer Automation Pack',
    file: 'freelancer-sample.json',
    industries: ['freelancer', 'consultant', 'contractor', 'sole trader', 'independent'],
    keywords: ['invoice reminder', 'overdue payment', 'client follow-up', 'proposal', 'timesheet'],
    description: 'Invoice reminders, overdue payment chasers, client follow-up sequences, proposal tracking.',
    price: '$39',
    url: 'https://payhip.com/b/ZKDRt',
  },
  {
    id: 'gym-fitness',
    name: 'Gym + Fitness Studio Automation Pack',
    file: 'gym-fitness-sample.json',
    industries: ['gym', 'fitness', 'personal trainer', 'pilates', 'yoga studio'],
    keywords: ['membership', 'class booking', 'renewal', 'attendance', 'trial', 'pt session'],
    description: 'Membership renewal reminders, class booking confirmations, attendance tracking, trial conversions.',
    price: '$49',
    url: 'https://payhip.com/b/6r7oV',
  },
  {
    id: 'healthcare',
    name: 'Healthcare + Practice Automation Pack',
    file: 'healthcare-sample.json',
    industries: ['healthcare', 'medical practice', 'physio', 'psychology', 'allied health'],
    keywords: ['appointment', 'recall', 'prescription', 'referral', 'patient', 'follow-up', 'waitlist'],
    description: 'Appointment reminders, recall sequences, referral tracking, patient follow-up flows.',
    price: '$49',
    url: 'https://payhip.com/b/MS3DO',
  },
  {
    id: 'hr-ops',
    name: 'HR + Ops Automation Pack',
    file: 'hr-ops-sample.json',
    industries: ['hr', 'human resources', 'operations', 'people ops', 'people team'],
    keywords: ['onboarding', 'offboarding', 'leave', 'timesheet', 'review', 'policy', 'compliance'],
    description: 'Employee onboarding/offboarding flows, leave request handling, performance review reminders.',
    price: '$49',
    url: 'https://payhip.com/b/Sjd5s',
  },
  {
    id: 'it-service-desk',
    name: 'IT Service Desk Automation Pack',
    file: 'it-service-desk-sample.json',
    industries: ['it', 'managed services', 'msp', 'helpdesk', 'sysadmin'],
    keywords: ['ticket', 'sla', 'escalation', 'alert', 'monitoring', 'incident', 'patch'],
    description: 'Ticket triage and SLA tracking, incident escalation, server alert routing, patch reminders.',
    price: '$49',
    url: 'https://payhip.com/b/R7VC6',
  },
  {
    id: 'legal-compliance',
    name: 'Legal + Compliance Automation Pack',
    file: 'legal-compliance-sample.json',
    industries: ['legal', 'law firm', 'compliance', 'regulatory', 'governance'],
    keywords: ['contract', 'deadline', 'renewal', 'filing', 'compliance', 'matter', 'billing'],
    description: 'Contract renewal alerts, matter deadline tracking, compliance filing reminders, time billing.',
    price: '$49',
    url: 'https://payhip.com/b/6qINi',
  },
  {
    id: 'logistics',
    name: 'Logistics + Shipping Automation Pack',
    file: 'logistics-sample.json',
    industries: ['logistics', 'shipping', 'freight', '3pl', 'courier', 'supply chain'],
    keywords: ['shipment', 'tracking', 'delivery', 'dispatch', 'eta', 'delay', 'carrier'],
    description: 'Shipment tracking notifications, delay alerts, dispatch confirmations, carrier updates.',
    price: '$49',
    url: 'https://payhip.com/b/fVPvt',
  },
  {
    id: 'marketing',
    name: 'Marketing Automation Pack',
    file: 'marketing-sample.json',
    industries: ['marketing', 'digital marketing', 'growth', 'demand gen', 'marketing team'],
    keywords: ['lead', 'campaign', 'email sequence', 'nurture', 'retargeting', 'report', 'analytics'],
    description: 'Lead nurture sequences, campaign performance reports, retargeting triggers, analytics digests.',
    price: '$49',
    url: 'https://payhip.com/b/rEfLt',
  },
  {
    id: 'nonprofit',
    name: 'Nonprofit + Community Automation Pack',
    file: 'nonprofit-sample.json',
    industries: ['nonprofit', 'charity', 'ngo', 'community org', 'association'],
    keywords: ['donor', 'volunteer', 'grant', 'event', 'fundraising', 'newsletter', 'membership'],
    description: 'Donor acknowledgement flows, volunteer coordination, grant deadline alerts, event management.',
    price: '$49',
    url: 'https://payhip.com/b/pwfdK',
  },
  {
    id: 'photography',
    name: 'Photography + Creative Studio Pack',
    file: 'photography-sample.json',
    industries: ['photography', 'videography', 'creative studio', 'design studio'],
    keywords: ['booking', 'gallery delivery', 'contract', 'invoice', 'shoot', 'proof', 'client portal'],
    description: 'Booking confirmations, gallery delivery notifications, contract signing reminders, invoice chasers.',
    price: '$49',
    url: 'https://payhip.com/b/UnlhY',
  },
  {
    id: 'project-mgmt',
    name: 'Project Management Automation Pack',
    file: 'project-mgmt-sample.json',
    industries: ['project management', 'pm', 'project manager', 'construction', 'consulting'],
    keywords: ['task', 'deadline', 'milestone', 'status update', 'risk', 'budget', 'stakeholder'],
    description: 'Task deadline alerts, milestone status updates, risk flag notifications, budget tracking.',
    price: '$49',
    url: 'https://payhip.com/b/hY0Oy',
  },
  {
    id: 'property-mgmt',
    name: 'Property Management Automation Pack',
    file: 'property-mgmt-sample.json',
    industries: ['property management', 'real estate', 'strata', 'landlord', 'property manager'],
    keywords: ['lease', 'rent', 'maintenance', 'inspection', 'renewal', 'tenant', 'arrears'],
    description: 'Rent arrears alerts, lease renewal reminders, maintenance request routing, inspection scheduling.',
    price: '$49',
    url: 'https://payhip.com/b/mzfoL',
  },
  {
    id: 'real-estate',
    name: 'Real Estate + Property Management Pack',
    file: 'real-estate-sample.json',
    industries: ['real estate', 'property', 'real estate agent', 'buyer agent'],
    keywords: ['listing', 'appraisal', 'open home', 'offer', 'settlement', 'vendor', 'buyer follow-up'],
    description: 'Listing management, open home follow-ups, offer tracking, settlement milestone notifications.',
    price: '$49',
    url: 'https://payhip.com/b/UuFgZ',
  },
  {
    id: 'recruitment',
    name: 'Recruitment + Hiring Automation Pack',
    file: 'recruitment-sample.json',
    industries: ['recruitment', 'hiring', 'talent acquisition', 'hr', 'recruiter'],
    keywords: ['application', 'interview', 'candidate', 'offer', 'rejection', 'pipeline', 'screening'],
    description: 'Application acknowledgements, interview scheduling, candidate pipeline updates, offer workflows.',
    price: '$49',
    url: 'https://payhip.com/b/RklJE',
  },
  {
    id: 'restaurant',
    name: 'Restaurant + Hospitality Automation Pack',
    file: 'restaurant-sample.json',
    industries: ['restaurant', 'cafe', 'hospitality', 'bar', 'food service'],
    keywords: ['reservation', 'booking', 'supplier', 'inventory', 'staff', 'review', 'no-show'],
    description: 'Reservation confirmations, supplier order automation, no-show follow-ups, review response drafts.',
    price: '$49',
    url: 'https://payhip.com/b/vwnIQ',
  },
  {
    id: 'saas-creator',
    name: 'SaaS + Creator Automation Pack',
    file: 'saas-creator-sample.json',
    industries: ['saas', 'software', 'startup', 'creator economy', 'product'],
    keywords: ['trial', 'churn', 'renewal', 'upgrade', 'feature announcement', 'mrr', 'cohort'],
    description: 'Trial-to-paid flows, churn prediction alerts, renewal reminders, feature announcement sequences.',
    price: '$49',
    url: 'https://payhip.com/b/fKNth',
  },
  {
    id: 'sales-crm',
    name: 'Sales + CRM Automation Pack',
    file: 'sales-crm-sample.json',
    industries: ['sales', 'crm', 'b2b sales', 'account management', 'business development'],
    keywords: ['lead', 'follow-up', 'pipeline', 'deal', 'proposal', 'close', 'demo', 'outreach'],
    description: 'Lead follow-up sequences, deal stage transitions, proposal reminders, pipeline hygiene alerts.',
    price: '$49',
    url: 'https://payhip.com/b/x7QDE',
  },
  {
    id: 'social-media',
    name: 'Social Media Automation Pack',
    file: 'social-media-sample.json',
    industries: ['social media', 'social media manager', 'brand', 'community manager'],
    keywords: ['post', 'schedule', 'engagement', 'comment', 'dm', 'analytics', 'report'],
    description: 'Post scheduling, engagement monitoring, DM response drafts, weekly analytics reports.',
    price: '$49',
    url: 'https://payhip.com/b/s4NiE',
  },
  {
    id: 'subscription',
    name: 'Subscription + Membership Automation Pack',
    file: 'subscription-sample.json',
    industries: ['subscription', 'membership', 'association', 'gym', 'club'],
    keywords: ['renewal', 'payment failed', 'churn', 'upgrade', 'downgrade', 'cancellation', 'win-back'],
    description: 'Renewal reminders, failed payment recovery, cancellation win-back sequences, upgrade prompts.',
    price: '$49',
    url: 'https://payhip.com/b/BktQJ',
  },
  {
    id: 'supply-chain',
    name: 'Supply Chain Automation Pack',
    file: 'supply-chain-sample.json',
    industries: ['supply chain', 'manufacturing', 'warehouse', 'procurement', 'operations'],
    keywords: ['purchase order', 'supplier', 'inventory', 'lead time', 'reorder', 'delivery', 'stock'],
    description: 'PO generation, supplier lead time tracking, low-stock reorder alerts, delivery confirmations.',
    price: '$49',
    url: 'https://payhip.com/b/u0N5c',
  },
  {
    id: 'veterinary',
    name: 'Veterinary + Pet Care Automation Pack',
    file: 'veterinary-sample.json',
    industries: ['veterinary', 'vet clinic', 'pet care', 'grooming', 'kennel'],
    keywords: ['appointment', 'vaccination', 'recall', 'pet', 'reminder', 'annual checkup'],
    description: 'Appointment reminders, vaccination recall sequences, annual checkup reminders, client follow-ups.',
    price: '$49',
    url: 'https://payhip.com/b/HyIpf',
  },
  {
    id: 'youtube-creator',
    name: 'YouTube Creator Automation Pack',
    file: 'youtube-creator-sample.json',
    industries: ['youtube', 'video creator', 'youtuber', 'podcast', 'video production'],
    keywords: ['upload', 'thumbnail', 'community post', 'comment moderation', 'analytics', 'sponsorship'],
    description: 'Upload checklists, community post scheduling, comment moderation alerts, sponsorship tracking.',
    price: '$49',
    url: 'https://payhip.com/b/DHmsB',
  },
];

module.exports = { PACKS };
